Repository tigergraph/CoPilot, pull requests merged in 2024-07, with the labels that each got.

#236 Gml 1803 resumable convo api
  copilot/app/routers/ui.py
Labels: huggingface_phi3

#243 feat(error handling): surface better error messages to api
  copilot/app/agent/agent_graph.py
  copilot/app/routers/inquiryai.py
  copilot/app/tools/generate_function.py
Labels: openai_gpt4o

#248 Gml 1824 regression test with cypher support and no hallucination and usefulness check
  common/prompts/aws_bedrock_claude3haiku/generate_function.txt
  common/prompts/aws_bedrock_claude3haiku/map_question_to_schema.txt
  common/prompts/aws_bedrock_titan/generate_function.txt
  common/prompts/aws_bedrock_titan/map_question_to_schema.txt
  common/prompts/azure_open_ai_gpt35_turbo_instruct/generate_function.txt
  common/prompts/azure_open_ai_gpt35_turbo_instruct/map_question_to_schema.txt
  common/prompts/gcp_vertexai_palm/generate_function.txt
  common/prompts/gcp_vertexai_palm/map_question_to_schema.txt
  common/prompts/llama_70b/generate_function.txt
  common/prompts/llama_70b/map_question_to_schema.txt
  common/prompts/openai_gpt4/generate_function.txt
  common/prompts/openai_gpt4/map_question_to_schema.txt
  copilot/app/agent/agent.py
  copilot/app/agent/agent_generation.py
  copilot/app/agent/agent_graph.py
  copilot/app/agent/agent_hallucination_check.py
  copilot/app/agent/agent_usefulness_check.py
  copilot/app/tools/generate_function.py
  copilot/app/tools/map_question_to_schema.py
  copilot/app/tools/validation_utils.py
  copilot/docs/notebooks/TransactionFraud_demo.ipynb
Labels: openai_gpt4o

#246 Issue #235: healthcheck uses hardcoded milvus config
  common/config.py
  copilot/app/routers/inquiryai.py
  copilot/app/routers/root.py
  copilot/app/routers/supportai.py
  copilot/app/routers/ui.py
Labels: openai_gpt4o

#249 Gml 1767 watsonx integration
  .github/workflows/build-test-ci.yaml
  common/config.py
  common/llm_services/__init__.py
  common/llm_services/ibm_watsonx_service.py
  copilot/app/agent/agent.py
  copilot/requirements.txt
  copilot/tests/run_tests.sh
  copilot/tests/test_watsonx_mistral-large.py
Labels: watsonx_mistral_large

#169 TCE-4255 feat(cicd): Integrate the CoPilot repo CI/CD Pipeline with TGCloud;
  .github/workflows/pre-merge-test.yml
Labels: enhancement
